---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--pre"

dependencies:
  galaxy: requirements.yml 
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python:
    - six
    - psutil
    - pywinrm
  exclude:
    python:
      - docker
    system:
      - python3-Cython

images:
  base_image:
    name: registry.fedoraproject.org/fedora:38

additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg


