---

    - name: Replace NOPASSWD with password requirement for cloud-user
      lineinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        regexp: '^cloud-user\s+ALL=\(ALL\)\s+NOPASSWD:ALL'
        line: 'cloud-user ALL=(ALL) ALL'
        owner: root
        group: root
        mode: '0440'

