---
controller_workflow:
  - name: WFJT - Configuration Management Day 2 Ops
    description: A workflow to Manage Day 2 Operations of the provisioned VM
    survey_enabled: false
    allow_simultaneous: false
    ask_variables_on_launch: false
    inventory:
    limit:
    scm_branch:
    ask_inventory_on_launch: false
    ask_scm_branch_on_launch: false
    ask_limit_on_launch: false
    webhook_service: ''
    webhook_credential:
    organization: "{{ aap_organizations[0].name }}"
    schedules: []
    simplified_workflow_nodes:
      - all_parents_must_converge: false
        identifier: "Retrieve VM Blueprint"
        unified_job_template: "Provisioning Demo"
        credentials: []
        success_nodes: 
          - "Initialize Workflow"
        failure_nodes: []
        always_nodes: []
      - all_parents_must_converge: false
        identifier: "Initialize Workflow"
        unified_job_template: 'JT - Workflow Init'
        credentials: []
        success_nodes: 
          - "Refresh Build inventory"
        failure_nodes: []
        always_nodes: []

      - all_parents_must_converge: true
        identifier: "Refresh Build inventory"
        unified_job_template: 'OCP Virt Prod'
        credentials: []
        success_nodes:
          - 'Apply OS Config'
        failure_nodes:
          - 'SNOW INC'
        always_nodes: []

      - all_parents_must_converge: true
        identifier: "Apply OS Config"
        unified_job_template: 'JT - RHEL - Apply OS Config'
        inventory: 'Demo Inventory - Prod'
        success_nodes:
          - 'Security Hardening'
        failure_nodes:
          - 'SNOW INC'
        always_nodes: []

      - all_parents_must_converge: true
        identifier: 'Security Hardening'
        unified_job_template: 'JT - RHEL - CIS Hardening'
        inventory: 'Demo Inventory - Prod'
        success_nodes:
          - 'Third Party Integrations'
        failure_nodes:
          - 'SNOW INC'
        always_nodes: []

      - all_parents_must_converge: true
        identifier: 'Third Party Integrations'
        unified_job_template: 'JT - RHEL - Third Party Integrations'
        inventory: 'Demo Inventory - Prod'
        success_nodes: 
          - 'Notify Success'
        failure_nodes:
          - 'SNOW INC'
        always_nodes: []

      - all_parents_must_converge: true
        identifier: 'Notify Success'
        unified_job_template: 'JT - Notify Success'
        credentials: []
        success_nodes: []
        failure_nodes: []
        always_nodes: []

      - all_parents_must_converge: false
        identifier: 'SNOW INC'
        unified_job_template: 'JT - SNOW - Raise Incident'
        credentials: []
        success_nodes: []
        failure_nodes: []
        always_nodes:
          - 'Notify Failure'

      - all_parents_must_converge: true
        identifier: 'Notify Failure'
        unified_job_template: 'JT - Notify Failure'
        credentials: []
        success_nodes: []
        failure_nodes: []
        always_nodes: []
