---
- name: Create OCPVIRT VM 
  hosts: localhost
  gather_facts: false

  collections:
    - redhat.openshift_virtualization
    - kubernetes.core
    - redhat.openshift
 
  vars_files:
    - ../vault/secrets.yml

  vars:
    v_ocp_cluster_api: https://api.cluster-4tj5d.dynamic.redhatworkshops.io:6443
    v_vm_name: demovm0001
    v_vm_namespace: mina
    v_vm_instancetype_new: u1.large
    v_vm_resources:
      u1.large:
        cpu: '2'
        memory: '8Gi'
      u1.xlarge:
        cpu: '4'
        memory: '16Gi'
    v_new_cpu: "{{ v_vm_resources[v_vm_instancetype_new].cpu | int }}"
    v_new_mem: "{{ v_vm_resources[v_vm_instancetype_new].memory }}"

  tasks:


    - debug: 
        var: v_new_cpu

    - name: Update VM on OCP cluster
      ansible.builtin.include_role:
        name: "../roles/ocpvirt-manage"
        tasks_from: 04-change-instance-type-vm.yml
