---
- name: Apply RHEL OS configs
  hosts: all
  become: true
  become_method: sudo
  collections:
    - community.general

  vars_files:
    - ../vault/secrets.yml
     
  tasks:

    - name: Subscribe the system to RHSM
      ansible.builtin.include_role:
        name: ../roles/rhel-manage
        tasks_from: 01_rhsm.yml

    - name: Subscribe the system to RHSM
      ansible.builtin.include_role:
        name: ../roles/rhel-manage
        tasks_from: 01_rhsm.yml

