---
- name: Create SNOW CI
  hosts: localhost
  gather_facts: false

  collections:
    - servicenow.itsm

  tasks:

    - name: Update Change Request to Implement state
      ansible.builtin.include_role:
        name: ../roles/snow-manage
        tasks_from: 09-close-crq.yml

