---
- name: Create Incident in SNOW 
  hosts: localhost
  gather_facts: false

  collections:
    - servicenow.itsm

     
  tasks:

    - name: Create VM on OCP cluster
      ansible.builtin.include_role:
        name: ../roles/snow-manage
        tasks_from: 04-create-incident.yml


