---
- name: Create SNOW CI
  hosts: localhost
  gather_facts: false

  collections:
    - servicenow.itsm

  vars:
     
  tasks:

    - name: Create VM on OCP cluster
      ansible.builtin.include_role:
        name: ../roles/snow-manage
        tasks_from: 02-update-ci.yml
