---
- name: Create SNOW CI
  hosts: localhost
  gather_facts: false

  collections:
    - itsm.servicenow

  tasks:

    - name: Create CMDB CI
      ansible.builtin.include_role:
        name: ../roles/snow-manage
        tasks_from: 01-create-ci.yml

    - name: Update Change Request to Implement state
      ansible.builtin.include_role:
        name: ../roles/snow-manage
        tasks_from: 08-update-crq.yml

