---
- name: Create SNOW CI
  hosts: localhost
  gather_facts: false

  collections:
    - itsm.servicenow

  vars:
     v_lcy_environment: production
     v_vm_name: "test010" 
     
  tasks:

    - name: Create VM on OCP cluster
      ansible.builtin.include_role:
        name: ../snow-manage
        tasks_from: 01-create-ci.yml
