---
- name: Apply CIS Benchmark security/compliance hardenning to the NEW RHEL 9 VM 
  hosts: all
  become: true
  become_method: sudo
  collections:
    - community.general

  tasks: 

    - name: Apply RHEL {{ ansible_distribution_major_version }}  CIS Compliance Hardenning
      ansible.builtin.include_role:
        name: rhel{{ ansible_distribution_major_version }}-cis
        tasks_from: rhel{{ ansible_distribution_major_version }}-playbook-cis.yml

#    - name: Run Openscap Scan and Upload Reports to Satellite Server
#      include_role:
#        name: theforeman.foreman_scap_client

#    - name: Run Openscap Scan and Upload Reports to Gitlab
#      include_role:
#        name: openscap_scan_reports

#    - name: Remove Local Prov User and Create Automation svc account for continuous remediation
#      include_role:
#        name: rhel_post_config
#        tasks_from: 99_create_accounts.yml

