---

    - name: Retrieve change requests by number
      servicenow.itsm.change_request_info:
        number: "{{ v_change_request_number }}"
      register: crq_info

    - name: Fail IF the CRQ is not in Scheduled State
      fail:
        msg: "Change Request is NOT YET ready for implementation .. Bye for now ! "
      when:  crq_info.records[0].state != "scheduled"


    - name: Updage Change Request
      servicenow.itsm.change_request:
        number: "{{ v_change_request_number }}"
        state: "implement"
      register: update_crq

    - debug:
        msg: "Change Request Updated : {{ update_crq.record.number }} "
      ignore_errors: true
