---

    - name: Link new CI to CRQ
      servicenow.itsm.change_request:
        number: "{{ v_change_request_number }}"
        other:
          cmdb_ci: "{{ new_ci_details.records[0].sys_id }}" 
      register: update_crq
      ignore_errors: true

    - name: Updage Change Request ti Implement Phase
      servicenow.itsm.change_request:
        number: "{{ v_change_request_number }}"
        state: "implement"
      register: update_crq

    - debug:
        msg: "Change Request Updated : {{ update_crq.record.number }} "
      ignore_errors: true
